version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - CONFIG_PATH=/app/config.yaml
    depends_on:
      - redis
      - qdrant
      - postgres
      - urltomarkdown

  urltomarkdown:
    build:
      context: .
      dockerfile: Dockerfile.urltomarkdown
    ports:
      - "1337:1337"
    environment:
      - PORT=1337

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=llm_toolkit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  qdrant_data:
  postgres_data: